### ISSUE TITLE
ConsoleLogger spreads messages into multiple lines in CloudWatch

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-log#189]
Adding the following code to a universal action that is deployed in AWS:
```
const obj = {
  a: '1',
  b: '2',
  c: '3',
};
log.info(`This is obj in log.info: ${JSON.stringify(obj, undefined, 2)}`);
console.log(`This is obj in console.log: ${JSON.stringify(obj, undefined, 2)}`);
```
I get the following log output in CloudWatch:
<img width="1237" alt="Screenshot 2021-05-06 at 18 35 58" src="https://user-images.githubusercontent.com/22323322/117334172-f7780780-ae99-11eb-878b-4e3a20f79afc.png">
where the stringified JSON is spread over multiple lines, which is not handy for larger objects.

If I replace ConsoleLogger's log implementation in https://github.com/adobe/helix-log/blob/586ee3aa4e3734dc3cf88797ed7ef04dd9c80b9b/src/log.js#L598-L590 with the following:
```
  _logImpl(str) {
    console.log(str);
  }
```
I get the expected output:
<img width="1266" alt="Screenshot 2021-05-06 at 18 39 00" src="https://user-images.githubusercontent.com/22323322/117334509-5d648f00-ae9a-11eb-855b-0c9b06ea73f9.png">

**Comment by tripodsan** [comment]
I suggest to log with:

```
log.info(`This is obj in log.info: `, obj);
```

**Comment by dominique-pfister** [comment]
Actually, the issue occurs with every message containing embedded linefeeds. To my knowledge, there is no satisfactory way to output such a message in CloudWatch:
- using `ConsoleLogger` I get multiple log messages as described, which makes it hard to look at search results without context.
- using `console.log` I get one message, but CloudWatch will prefix it with timestamp, request ID and log level as described here: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-logging.html#node-logging-output, which clutters up the list of log messages in CloudWatch.
