### ISSUE TITLE
Setup semantic-release

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#2]

**Comment by tripodsan** [comment]
@trieloff @koraa I setup the config for semantic-release but didn't enable it, until we are ready.
what is missing:
- add NPM_TOKEN and GITHUB_TOKEN to circleci env
- rename `master_disabled` to `master` in `.circle/config.yaml`

**Comment by trieloff** [comment]
I've added `GH_TOKEN` and `NPM_TOKEN`

**Comment by tripodsan** [comment]
thanks.
