### ISSUE TITLE
lowercase all jsdoc native types

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#28]
as per:
https://jsdoc.app/tags-type.html
which refers to:
https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System

all the native types should be lowercase:

eg:

```
 * @param {String|Integer} name - The path of the file to log to
 *   OR the unix file descriptor to log to.
 * @param {Object} opts – Configuration object
```

should be

```
 * @param {string|number} name - The path of the file to log to
 *   OR the unix file descriptor to log to.
 * @param {Object} opts – Configuration object
```

also, instead of `any` we should use `*`.

**Comment by koraa** [comment]
Didn't know that! Thanks!
I will be happy to receive a PR for that!
