### ISSUE TITLE
Add serialize option to ignore log-data for simple message format

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#34]
when using the default console logger, any log-data is serialized. this is a problem when using the logger as bunyan stream. eg:

```
2019-09-19T05:53:10.702Z       stderr: testing invocation via bunyan. { timestamp: 2019-09-19T05:53:10.701Z, name: 'bot/login@0.2.1', hostname: '7ce869d8ec3a', pid: 1, ow: { activationId: '77b3898c54e24ea1b3898c54e23ea198', actionName: '/tripod/bot/login@0.2.1' }, v: 0, bunyanLevel: 30 }
2019-09-19T05:53:10.703Z       stderr: [WARN] testing invocation via bunyan. { timestamp: 2019-09-19T05:53:10.702Z, name: 'bot/login@0.2.1', hostname: '7ce869d8ec3a', pid: 1, ow: { activationId: '77b3898c54e24ea1b3898c54e23ea198', actionName: '/tripod/bot/login@0.2.1' }, v: 0, bunyanLevel: 40 }
```

it would be nice, if we could just disable the serialization of the non-string message parts.

eg:

```
rootLogger.loggers.set('default', new ConsoleLogger({
  level: 'info',
  ignoreObjectSerialization: true,
}));
```

**Comment by tripodsan** [comment]
workaround:
```
rootLogger.loggers.set('default', new ConsoleLogger({
  level: 'info',
  formatter: (msg, opts) => messageFormatSimple([msg[0]], opts),
}));
```

**Comment by koraa** [comment]
Interesting suggestion! I totally get why this is desired, especially for the ConsoleLogger combined with bunyan.

As you already suggested, I think the right place to implement this would be the formatter,  not the logger itself…

Unfortunately, I am not sure how to reconcile this with normal helix-log operation…The last element tof the message is not guaranteed to be log data; it is just another regular part of the message that the json loggers – by convention – treat like it potentially could contain json data (while taking great care not to fail if this is not the case). It's a convention introduced to stay compatible with the common use case `console.log("My error was: ", exception)` and other similar cases; it is the part of helix-log I am least happy with,

I think a better way to implement this functionality would be this:

```
const { last, type } = require('ferrum');
class messageFormatConsoleNoBunyan = (msg, opts) => {a
  // Reasonable heuristic to detect bunyan messages
  const isBunyanMsg = true
      && type(last(msg)) === Object
      && type(last(msg).v) === Number
      && type(last(msg).bunyanLevel) === Number;
  return messageFormatConsole(isBunyanMsg ? list(initial(msg)) : msg, opts);
};
```

I am a bit reluctant to integrate this into helix log; I would like the things that are part of helix-log to be easy to use and foolproof…and considering that bunyan itself just logs json to the console which is even harder to read it might not be strictly necessary?
However, this should not stop us from using the code; is this feature required in mutliple repos? If not we may just keep this formatter in the helix bot code and reevaluate inclusion in helix log later?

**Comment by koraa** [comment]
NOTE: The implementation I suggested should not affect (most) normal helix log usage; for bunyan messages themselves your suggestion works too of course…
