### ISSUE TITLE
coralogix: severity does not match log level

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-log#57]
**Description**
Coralogix log entries with `"level": "info"`have `Severity: ERROR`. An example:

```
Timestamp: 18/10/2019 14:36:29.894 pm
Severity: 5 (ERROR)
{
   "level"  :  "info" ,
   "ow"  : {
     "activationId"  :  "??????" ,
     "actionName"  :  "/helix/helix-services-private/static@1.5.7" ,
     "transactionId"  :  "??????" 
  },
   "message"  :  "delivering error /404.html 404" ,
   "timestamp"  :  "2019-10-18T12:36:29.894Z" 
}
```

**To Reproduce**
Go to https://helix.coralogix.com/#/query/logs?id=1Xf1jU2SH7a and compare log level and severity.

**Expected behavior**
Log entries with `info` level should have severity `3: info` 

**Additional context**
`helix-static@1.5.7` creates coralogix log entries with level `info` and severity `5: error`. `dispatch@2.2.1` OTOH is creating coralogix log entries with level `info` and severity `3: info`. Both are using `helix-log@3.0.0`...

**Comment by koraa** [comment]
Good catch! Thank you! Could you provide a PR to fix this?

**Comment by stefan-guggisberg** [comment]
I looked at the code and couldn't spot the problem. The mapping level->severity seems ok. I have no clue where the problem is.

**Comment by koraa** [comment]
OK, thanks for taking a look!

**Comment by tripodsan** [comment]
related to: https://github.com/adobe/openwhisk-action-utils/issues/21

**Comment by tripodsan** [comment]
helix-static uses directly the `rootLogger` where as `helix-dispatch` uses the bunyan logger of `params.__ow_logger`.

**Comment by koraa** [comment]
I am unable to reproduce this; either with or without a BunyanStreamLogger in the loop. Are you sure you are on the most recent version of helix-log? Could you please provide steps to reproduce?

**Comment by koraa** [comment]
Toby & Stefan found it; coralogix automatically sets severity to error if the text contains "error". >_>

**Comment by stefan-guggisberg** [comment]
yep, it's a coralogix feature... 

closing the issue
