### ISSUE TITLE
BigDate tests failing

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#65]
**Description**
When I run the tests, I get:

```
  1) BigDate
       construction, toISOString(), preciseTime()
         from sparse components:

      AssertionError [ERR_ASSERTION]: The values are not equal!
      + expected - actual

      -'2019-01-31T15:00:00.000000000Z'
      +'2019-01-31T23:00:00.000000000Z'

      at Context.it (test/big-date.js:32:9)
```

(maybe because I have a different timezone or locale?)

```
$ date
Fri Nov 15 15:08:03 JST 2019
```

**Comment by koraa** [comment]
Thanks for reporting this!

Unfortunately – since this appears to be a time zone issue – I won't be able to reproduce. Could you please go ahead and take responsibility for fixing this?

You could start by replacing the test with this:

```
    it('from sparse components', () => {
      ckEqual(
        new BigDate(2019, 01),
        new BigDate(new Date(2019, 01)));
    });
```

Which will probably do the trick anyways…
