### ISSUE TITLE
Remove winston interface from helix-log

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#81]
I think we should remove the winston dependency from helix-log.
see https://github.com/adobe/helix-log/pull/76#issuecomment-565859451.

**Comment by koraa** [comment]
The PR you are referring to does not introduce a winston dependency. It introduces a dependency to `winston-transport` which is relatively small and only provides just a winston transport interface base class.

A winston dependency is introduced as a dev-dependency for testing.

I too am not quite happy about introducing this TBH, but IMHO it's the best way of using helix log in helix-shared/Logger.js logging backend…

Given that the winston-transport latency is not that big I do not not see a big need to push this into a separate package…

I do agree it would be preferable to get rid of both the Bunyan and the Winston interfaces, but right now I see this more as a long term goal…maybe we can start by using helix-log directly in new code and refactoring existing code bit by bit…

**Comment by tripodsan** [comment]
you are correct.
