### ISSUE TITLE
Suppress multiple versions warning for same version

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-log#96]
In project `adobe/helix-index-file`, I'm currently seeing a warning when running the tests:
```
Multiple versions of adobe/helix-log in the same process! Using one loaded first!
{ used: { version: '4.5.0', filename: './helix-index-files/node_modules/@adobe/helix-log/src/index.js' },
discarded: { version: '4.5.0', filename: './helix-index-files/node_modules/@adobe/helix-status/node_modules/@adobe/helix-log/src/index.js' } }
```
Can't we suppress that message when the 2 versions clashing are actually the same?

**Comment by koraa** [comment]
Having two versions of helix-log in the tree is in no case optimal…e.g. the JsonifyForLog can get seriously confused…can you check why the two versions aren't being consolidated by npm install?

**Comment by dominique-pfister** [comment]
Right, after executing `npm ddp` the duplicate was removed.

**Comment by koraa** [comment]
Thanks for taking the time to check :)

**Comment by tripodsan** [comment]
I think we should use the `^` notation when referencing helix-log. this would allow npm to better dedupe the module, even for minor version updates.

**Comment by dominique-pfister** [comment]
Thanks for your quick reply, @koraa :-)
